[build]
  command = "gatsby build"
  publish = "public/"

[dev]
  command = "gatsby develop"

[[plugins]]
  package = "@netlify/plugin-gatsby"

[template.environment]
  COURIER_AUTH_TOKEN = "Courier Auth Token"
  COURIER_EVENT = "Courier Notification ID"
  COURIER_RECIPIENT = "Courier Profile ID"
